version: '3.8'

services:
  book-service:
    platform: linux/amd64
    build: .
    container_name: book-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookdb
      - NODE_ENV=development
    volumes:
      - .:/app  # Mounts local project into container
      - /app/node_modules  # Prevents overwriting node_modules inside container
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpwd
    
  mongo-express:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:rootpwd@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=root      # New basicAuth username
      - ME_CONFIG_BASICAUTH_PASSWORD=rootpwd  # New basicAuth password
    networks:
      - app-network
    ports:
      - "8081:8081"

volumes:
  mongo-data:

networks:
  app-network:
